# Generated by Django 4.2.6 on 2023-10-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_aeropuerto_alter_vuelo_destino_alter_vuelo_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='destino',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='origen',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Aeropuerto',
        ),
    ]
